#!/bin/sh

ant classesjar

cp lib/sootclasses-trunk.jar ../rootbeer1/lib/sootclasses-rbclassload.jar

mvn install:install-file -Dfile=lib/sootclasses-trunk.jar -DgroupId=soot \
    -DartifactId=soot -Dversion=rb-1.0 -Dpackaging=jar 

